myTuple = (9, 1, 3, 4, 6)
print(myTuple)
myList = list(myTuple)
print(myList)
myList.append(12)
print(myList)
myTuple = tuple(myList)
print(myTuple)
Tuple2 = (100, 200, 300, 400)
print(myTuple[1:4])
myTuple += Tuple2
print(myTuple)
myTuple += (500,)
print(myTuple)